import { Router } from 'express';
import { getWithdrawals, createWithdrawal, approveWithdrawal, rejectWithdrawal } from '../controllers/withdrawalController.js';
import { authenticateToken } from '../middleware/auth.js';
const router = Router();
router.use(authenticateToken);
router.get('/', getWithdrawals);
router.post('/', createWithdrawal);
router.put('/:id/approve', approveWithdrawal);
router.put('/:id/reject', rejectWithdrawal);
export default router;
